2020-12-16 11:51:54 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 11:51:54 [fileLogger] [INFO] : server system:Windows
2020-12-16 11:53:50 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 11:53:50 [fileLogger] [INFO] : server system:Windows
2020-12-16 11:54:20 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 11:54:20 [fileLogger] [INFO] : server system:Windows
2020-12-16 13:14:57 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 13:14:57 [fileLogger] [INFO] : server system:Windows
2020-12-16 13:16:18 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 13:16:18 [fileLogger] [INFO] : server system:Windows
2020-12-16 13:16:40 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 13:16:40 [fileLogger] [INFO] : server system:Windows
2020-12-16 13:17:37 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 13:17:37 [fileLogger] [INFO] : server system:Windows
2020-12-16 13:17:54 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 13:17:54 [fileLogger] [INFO] : server system:Windows
2020-12-16 13:18:11 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 13:18:11 [fileLogger] [INFO] : server system:Windows
2020-12-16 13:18:23 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 13:18:23 [fileLogger] [INFO] : server system:Windows
2020-12-16 13:23:18 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 13:23:18 [fileLogger] [INFO] : server system:Windows
2020-12-16 13:23:55 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 13:23:55 [fileLogger] [INFO] : server system:Windows
2020-12-16 13:24:01 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 13:24:01 [fileLogger] [INFO] : server system:Windows
2020-12-16 13:24:25 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 13:24:25 [fileLogger] [INFO] : server system:Windows
2020-12-16 13:30:50 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 13:30:50 [fileLogger] [INFO] : server system:Windows
2020-12-16 13:32:27 [tornado.general] [INFO] : F:\lance\pythons\pythonspace\base_tornado\utils\logger.py modified; restarting server
2020-12-16 13:33:45 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 13:33:45 [fileLogger] [INFO] : server system:Windows
2020-12-16 13:34:18 [tornado.general] [INFO] : F:\lance\pythons\pythonspace\base_tornado\utils\logger.py modified; restarting server
2020-12-16 14:25:45 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 14:25:45 [fileLogger] [INFO] : server system:Windows
2020-12-16 14:26:51 [tornado.general] [INFO] : F:\lance\pythons\pythonspace\base_tornado\api\user\view.py modified; restarting server
2020-12-16 14:27:45 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 14:27:45 [fileLogger] [INFO] : server system:Windows
2020-12-16 14:28:04 [tornado.access] [INFO] : 200 POST /base_tornado/user (192.168.1.134) 2.00ms
2020-12-16 14:28:19 [tornado.general] [INFO] : F:\lance\pythons\pythonspace\base_tornado\api\user\view.py modified; restarting server
2020-12-16 14:28:22 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 14:28:22 [fileLogger] [INFO] : server system:Windows
2020-12-16 14:28:24 [fileLogger] [ERROR] : Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x0541EA50>
Traceback (most recent call last):
  File "F:\lance\pythons\pythonspace\base_tornado\api\base\service.py", line 90, in find_one
    return await self.read_mysql_db.get(self.model, *args, **kwargs)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 182, in get
    result = await self.execute(query)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 271, in execute
    query = self._swap_database(query)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 381, in _swap_database
    "different. Query: %s Manager: %s" % (database, self.database)
AssertionError: Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x0541EA50>
2020-12-16 14:28:24 [fileLogger] [ERROR] : Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x0541EA50>
2020-12-16 14:28:24 [fileLogger] [INFO] : Rollback Transaction...
2020-12-16 14:28:24 [tornado.access] [INFO] : 200 POST /base_tornado/user (192.168.1.134) 25.07ms
2020-12-16 14:32:29 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 14:32:29 [fileLogger] [INFO] : server system:Windows
2020-12-16 14:32:31 [fileLogger] [ERROR] : Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x0518FA90>
Traceback (most recent call last):
  File "F:\lance\pythons\pythonspace\base_tornado\api\base\service.py", line 90, in find_one
    return await self.read_mysql_db.get(self.model, *args, **kwargs)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 182, in get
    result = await self.execute(query)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 271, in execute
    query = self._swap_database(query)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 381, in _swap_database
    "different. Query: %s Manager: %s" % (database, self.database)
AssertionError: Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x0518FA90>
2020-12-16 14:32:31 [fileLogger] [ERROR] : Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x0518FA90>
2020-12-16 14:32:31 [fileLogger] [INFO] : Rollback Transaction...
2020-12-16 14:32:31 [tornado.access] [INFO] : 200 POST /base_tornado/user (192.168.1.134) 15.04ms
2020-12-16 14:33:39 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 14:33:39 [fileLogger] [INFO] : server system:Windows
2020-12-16 14:33:41 [tornado.access] [INFO] : 200 POST /base_tornado/user (192.168.1.134) 2.01ms
2020-12-16 14:33:47 [tornado.access] [INFO] : 200 POST /base_tornado/user (192.168.1.134) 7.02ms
2020-12-16 14:33:57 [fileLogger] [ERROR] : Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x051B1A90>
Traceback (most recent call last):
  File "F:\lance\pythons\pythonspace\base_tornado\api\base\service.py", line 90, in find_one
    return await self.read_mysql_db.get(self.model, *args, **kwargs)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 182, in get
    result = await self.execute(query)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 271, in execute
    query = self._swap_database(query)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 381, in _swap_database
    "different. Query: %s Manager: %s" % (database, self.database)
AssertionError: Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x051B1A90>
2020-12-16 14:33:57 [fileLogger] [ERROR] : Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x051B1A90>
2020-12-16 14:33:57 [fileLogger] [INFO] : Rollback Transaction...
2020-12-16 14:33:57 [tornado.access] [INFO] : 200 POST /yzg_openapi/user (192.168.1.134) 15.04ms
2020-12-16 14:34:48 [fileLogger] [ERROR] : Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x051B1A90>
Traceback (most recent call last):
  File "F:\lance\pythons\pythonspace\base_tornado\api\base\service.py", line 90, in find_one
    return await self.read_mysql_db.get(self.model, *args, **kwargs)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 182, in get
    result = await self.execute(query)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 271, in execute
    query = self._swap_database(query)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 381, in _swap_database
    "different. Query: %s Manager: %s" % (database, self.database)
AssertionError: Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x051B1A90>
2020-12-16 14:34:48 [fileLogger] [ERROR] : Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x051B1A90>
2020-12-16 14:34:48 [fileLogger] [INFO] : Rollback Transaction...
2020-12-16 14:34:48 [tornado.access] [INFO] : 200 POST /yzg_openapi/user (192.168.1.134) 26296.82ms
2020-12-16 14:38:01 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 14:38:01 [fileLogger] [INFO] : server system:Windows
2020-12-16 14:38:41 [fileLogger] [ERROR] : Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x05BB0AF0>
Traceback (most recent call last):
  File "F:\lance\pythons\pythonspace\base_tornado\api\base\service.py", line 90, in find_one
    return await self.read_mysql_db.get(self.model, *args, **kwargs)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 182, in get
    result = await self.execute(query)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 271, in execute
    query = self._swap_database(query)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 381, in _swap_database
    "different. Query: %s Manager: %s" % (database, self.database)
AssertionError: Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x05BB0AF0>
2020-12-16 14:38:41 [fileLogger] [ERROR] : Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x05BB0AF0>
2020-12-16 14:38:41 [fileLogger] [INFO] : Rollback Transaction...
2020-12-16 14:38:41 [tornado.access] [INFO] : 200 POST /yzg_openapi/user (192.168.1.134) 30786.84ms
2020-12-16 14:38:49 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 14:38:49 [fileLogger] [INFO] : server system:Windows
2020-12-16 14:38:52 [fileLogger] [ERROR] : Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x04F9ECF0>
Traceback (most recent call last):
  File "F:\lance\pythons\pythonspace\base_tornado\api\base\service.py", line 56, in insert
    return await self.write_mysql_db.create(self.model, **kwargs)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 193, in create
    pk = await self.execute(query)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 271, in execute
    query = self._swap_database(query)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 381, in _swap_database
    "different. Query: %s Manager: %s" % (database, self.database)
AssertionError: Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x04F9ECF0>
2020-12-16 14:38:52 [fileLogger] [ERROR] : Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x04F9ECF0>
2020-12-16 14:38:52 [fileLogger] [INFO] : Rollback Transaction...
2020-12-16 14:38:52 [tornado.access] [INFO] : 200 POST /yzg_openapi/user (192.168.1.134) 13.03ms
2020-12-16 14:39:23 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 14:39:23 [fileLogger] [INFO] : server system:Windows
2020-12-16 14:39:25 [fileLogger] [ERROR] : Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x050D0470>
Traceback (most recent call last):
  File "F:\lance\pythons\pythonspace\base_tornado\api\base\service.py", line 90, in find_one
    return await self.read_mysql_db.get(self.model, *args, **kwargs)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 182, in get
    result = await self.execute(query)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 271, in execute
    query = self._swap_database(query)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 381, in _swap_database
    "different. Query: %s Manager: %s" % (database, self.database)
AssertionError: Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x050D0470>
2020-12-16 14:39:25 [fileLogger] [ERROR] : Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x050D0470>
2020-12-16 14:39:25 [fileLogger] [INFO] : Rollback Transaction...
2020-12-16 14:39:25 [tornado.access] [INFO] : 200 POST /yzg_openapi/user (192.168.1.134) 16.04ms
2020-12-16 14:39:44 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 14:40:43 [fileLogger] [INFO] : server system:Windows
2020-12-16 14:41:07 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 14:41:10 [fileLogger] [INFO] : server system:Windows
2020-12-16 14:41:14 [fileLogger] [ERROR] : Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x054BFAD0>
Traceback (most recent call last):
  File "F:\lance\pythons\pythonspace\base_tornado\api\base\service.py", line 90, in find_one
    return await self.read_mysql_db.get(self.model, *args, **kwargs)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 182, in get
    result = await self.execute(query)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 271, in execute
    query = self._swap_database(query)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 381, in _swap_database
    "different. Query: %s Manager: %s" % (database, self.database)
AssertionError: Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x054BFAD0>
2020-12-16 14:41:14 [fileLogger] [ERROR] : Error, query's database and manager's database are different. Query: None Manager: <peewee_async.PooledMySQLDatabase object at 0x054BFAD0>
2020-12-16 14:41:14 [fileLogger] [INFO] : Rollback Transaction...
2020-12-16 14:41:14 [tornado.access] [INFO] : 200 POST /yzg_openapi/user (192.168.1.134) 15.04ms
2020-12-16 14:46:14 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 14:46:14 [fileLogger] [INFO] : server system:Windows
2020-12-16 14:46:16 [fileLogger] [INFO] : Commit Transaction...
2020-12-16 14:46:16 [tornado.access] [INFO] : 200 POST /yzg_openapi/user (192.168.1.134) 243.65ms
2020-12-16 14:47:09 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 14:47:09 [fileLogger] [INFO] : server system:Windows
2020-12-16 14:47:18 [tornado.general] [INFO] : F:\lance\pythons\pythonspace\base_tornado\api\base\model.py modified; restarting server
2020-12-16 14:48:09 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 14:48:09 [fileLogger] [INFO] : server system:Windows
2020-12-16 14:48:10 [fileLogger] [INFO] : Rollback Transaction...
2020-12-16 14:48:10 [tornado.access] [INFO] : 200 POST /yzg_openapi/user (192.168.1.134) 144.38ms
2020-12-16 14:49:00 [fileLogger] [INFO] : Rollback Transaction...
2020-12-16 14:49:06 [tornado.application] [ERROR] : Uncaught exception POST /yzg_openapi/user (192.168.1.134)
HTTPServerRequest(protocol='http', host='192.168.1.134:8010', method='POST', uri='/yzg_openapi/user', version='HTTP/1.1', remote_ip='192.168.1.134')
Traceback (most recent call last):
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "F:\lance\pythons\pythonspace\base_tornado\api\user\view.py", line 22, in post
    res, code = await UserService.instance().user_create(**kwargs)
  File "F:\lance\pythons\pythonspace\base_tornado\utils\transaction_util.py", line 23, in wrapper
    await transaction.rollback()
TypeError: object int can't be used in 'await' expression
2020-12-16 14:49:06 [tornado.access] [ERROR] : 500 POST /yzg_openapi/user (192.168.1.134) 38020.78ms
2020-12-16 14:49:14 [fileLogger] [INFO] : Rollback Transaction...
2020-12-16 14:49:14 [tornado.access] [INFO] : 200 POST /yzg_openapi/user (192.168.1.134) 3769.20ms
2020-12-16 14:50:48 [tornado.general] [INFO] : F:\lance\pythons\pythonspace\base_tornado\utils\transaction_util.py modified; restarting server
2020-12-16 15:11:00 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 15:11:00 [fileLogger] [INFO] : server system:Windows
2020-12-16 15:11:17 [fileLogger] [INFO] : Rollback Transaction...
2020-12-16 15:11:17 [tornado.access] [INFO] : 200 POST /yzg_openapi/user (192.168.1.134) 73.19ms
2020-12-16 15:12:21 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 15:12:21 [fileLogger] [INFO] : server system:Windows
2020-12-16 15:13:59 [tornado.general] [INFO] : F:\lance\pythons\pythonspace\base_tornado\api\user\service.py modified; restarting server
2020-12-16 15:14:34 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 15:14:34 [fileLogger] [INFO] : server system:Windows
2020-12-16 15:14:36 [fileLogger] [WARNING] : Rollback Transaction...
2020-12-16 15:14:36 [tornado.access] [INFO] : 200 POST /yzg_openapi/user (192.168.1.134) 82.22ms
2020-12-16 15:17:10 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 15:17:10 [fileLogger] [INFO] : server system:Windows
2020-12-16 15:17:12 [tornado.general] [INFO] : F:\lance\pythons\pythonspace\base_tornado\api\user\service.py modified; restarting server
2020-12-16 15:17:19 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 15:17:19 [fileLogger] [INFO] : server system:Windows
2020-12-16 15:17:31 [fileLogger] [WARNING] : Rollback Transaction...
2020-12-16 15:17:31 [tornado.access] [INFO] : 200 POST /yzg_openapi/user (192.168.1.134) 347.93ms
2020-12-16 15:17:46 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 15:17:46 [fileLogger] [INFO] : server system:Windows
2020-12-16 15:18:04 [fileLogger] [WARNING] : Commit Transaction...
2020-12-16 15:18:04 [tornado.access] [INFO] : 200 POST /yzg_openapi/user (192.168.1.134) 403.07ms
2020-12-16 15:18:22 [fileLogger] [WARNING] : Rollback Transaction...
2020-12-16 15:18:22 [tornado.access] [INFO] : 200 POST /yzg_openapi/user (192.168.1.134) 14.04ms
2020-12-16 15:18:51 [tornado.general] [INFO] : F:\lance\pythons\pythonspace\base_tornado\api\user\service.py modified; restarting server
2020-12-16 15:18:59 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 15:18:59 [fileLogger] [INFO] : server system:Windows
2020-12-16 15:19:01 [fileLogger] [WARNING] : Rollback Transaction...
2020-12-16 15:19:01 [tornado.access] [INFO] : 200 POST /yzg_openapi/user (192.168.1.134) 19.05ms
2020-12-16 15:20:05 [tornado.general] [INFO] : F:\lance\pythons\pythonspace\base_tornado\api\user\urls.py modified; restarting server
2020-12-16 16:11:51 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 16:11:51 [fileLogger] [INFO] : server system:Windows
2020-12-16 16:12:06 [fileLogger] [WARNING] : Rollback Transaction...
2020-12-16 16:12:06 [tornado.access] [INFO] : 200 POST /yzg_openapi/user/management (192.168.1.134) 23.06ms
2020-12-16 16:12:11 [fileLogger] [INFO] : Commit Transaction...
2020-12-16 16:12:11 [tornado.access] [INFO] : 200 POST /yzg_openapi/user/management (192.168.1.134) 390.04ms
2020-12-16 16:13:02 [fileLogger] [INFO] : Commit Transaction...
2020-12-16 16:13:02 [tornado.access] [INFO] : 200 PUT /yzg_openapi/user/management (192.168.1.134) 427.90ms
2020-12-16 16:13:17 [fileLogger] [INFO] : Commit Transaction...
2020-12-16 16:13:17 [tornado.access] [INFO] : 200 PUT /yzg_openapi/user/management (192.168.1.134) 357.80ms
2020-12-16 16:13:21 [fileLogger] [WARNING] : Rollback Transaction...
2020-12-16 16:13:21 [tornado.access] [INFO] : 200 PUT /yzg_openapi/user/management (192.168.1.134) 7.02ms
2020-12-16 16:13:52 [fileLogger] [ERROR] : 'coroutine' object has no attribute 'delete'
Traceback (most recent call last):
  File "F:\lance\pythons\pythonspace\base_tornado\api\base\service.py", line 255, in delete
    return await self.write_mysql_db.delete(obj=obj)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 251, in delete
    query = obj.delete().where(obj._pk_expr())
AttributeError: 'coroutine' object has no attribute 'delete'
2020-12-16 16:13:52 [fileLogger] [ERROR] : 'coroutine' object has no attribute 'delete'
2020-12-16 16:13:52 [fileLogger] [WARNING] : Rollback Transaction...
2020-12-16 16:13:52 [tornado.access] [INFO] : 200 DELETE /yzg_openapi/user/management/48 (192.168.1.134) 7.02ms
2020-12-16 16:14:03 [fileLogger] [ERROR] : 'coroutine' object has no attribute 'delete'
Traceback (most recent call last):
  File "F:\lance\pythons\pythonspace\base_tornado\api\base\service.py", line 255, in delete
    return await self.write_mysql_db.delete(obj=obj)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 251, in delete
    query = obj.delete().where(obj._pk_expr())
AttributeError: 'coroutine' object has no attribute 'delete'
2020-12-16 16:14:03 [fileLogger] [ERROR] : 'coroutine' object has no attribute 'delete'
2020-12-16 16:14:03 [fileLogger] [WARNING] : Rollback Transaction...
2020-12-16 16:14:03 [tornado.access] [INFO] : 200 DELETE /yzg_openapi/user/management/48 (192.168.1.134) 6.02ms
2020-12-16 16:14:55 [fileLogger] [ERROR] : 'coroutine' object has no attribute 'delete'
Traceback (most recent call last):
  File "F:\lance\pythons\pythonspace\base_tornado\api\base\service.py", line 255, in delete
    return await self.write_mysql_db.delete(obj=obj)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 251, in delete
    query = obj.delete().where(obj._pk_expr())
AttributeError: 'coroutine' object has no attribute 'delete'
2020-12-16 16:14:55 [fileLogger] [ERROR] : 'coroutine' object has no attribute 'delete'
2020-12-16 16:14:55 [fileLogger] [WARNING] : Rollback Transaction...
2020-12-16 16:14:55 [tornado.access] [INFO] : 200 DELETE /yzg_openapi/user/management/48 (192.168.1.134) 9190.37ms
2020-12-16 16:17:08 [tornado.general] [INFO] : F:\lance\pythons\pythonspace\base_tornado\api\user\service.py modified; restarting server
2020-12-16 16:17:19 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 16:17:19 [fileLogger] [INFO] : server system:Windows
2020-12-16 16:17:25 [fileLogger] [INFO] : Commit Transaction...
2020-12-16 16:17:25 [tornado.access] [INFO] : 200 DELETE /yzg_openapi/user/management/48 (192.168.1.134) 3568.46ms
2020-12-16 16:18:14 [tornado.access] [INFO] : 200 POST /yzg_openapi/user/list (192.168.1.134) 2.01ms
2020-12-16 16:18:25 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 16:18:25 [fileLogger] [INFO] : server system:Windows
2020-12-16 16:18:26 [fileLogger] [ERROR] : '>' not supported between instances of 'dict' and 'int'
2020-12-16 16:18:26 [tornado.access] [INFO] : 200 POST /yzg_openapi/user/list (192.168.1.134) 5.01ms
2020-12-16 16:20:58 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 16:20:58 [fileLogger] [INFO] : server system:Windows
2020-12-16 16:21:15 [tornado.access] [INFO] : 200 POST /yzg_openapi/user/list (192.168.1.134) 12877.25ms
2020-12-16 16:21:33 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 16:21:33 [fileLogger] [INFO] : server system:Windows
2020-12-16 16:21:39 [tornado.access] [INFO] : 200 POST /yzg_openapi/user/list (192.168.1.134) 15.04ms
2020-12-16 16:21:59 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 16:21:59 [fileLogger] [INFO] : server system:Windows
2020-12-16 16:22:01 [fileLogger] [ERROR] : type object 'User' has no attribute 'io'
2020-12-16 16:22:01 [tornado.access] [INFO] : 200 POST /yzg_openapi/user/list (192.168.1.134) 3.01ms
2020-12-16 16:22:09 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 16:22:10 [fileLogger] [INFO] : server system:Windows
2020-12-16 16:22:15 [tornado.access] [INFO] : 200 POST /yzg_openapi/user/list (192.168.1.134) 16.04ms
2020-12-16 16:23:04 [fileLogger] [ERROR] : (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''10' OFFSET ''' at line 1")
Traceback (most recent call last):
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 1448, in _run_sql
    await cursor.execute(operation, *args, **kwargs)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\aiomysql\cursors.py", line 239, in execute
    await self._query(query)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\aiomysql\cursors.py", line 457, in _query
    await conn.query(q)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\aiomysql\connection.py", line 428, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\aiomysql\connection.py", line 622, in _read_query_result
    await result.read()
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\aiomysql\connection.py", line 1105, in read
    first_packet = await self.connection._read_packet()
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\aiomysql\connection.py", line 593, in _read_packet
    packet.check_error()
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''10' OFFSET ''' at line 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\lance\pythons\pythonspace\base_tornado\api\base\service.py", line 183, in list_paginate
    results = await self.read_mysql_db.execute(sql)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 272, in execute
    return (await execute(query))
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 432, in execute
    return (await coroutine(query))
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 570, in select
    cursor = await _execute_query_async(query)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 1465, in _execute_query_async
    return (await _run_sql(database, *query.sql()))
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 1453, in _run_sql
    return cursor
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee.py", line 2831, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee.py", line 183, in reraise
    raise value.with_traceback(tb)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\peewee_async.py", line 1448, in _run_sql
    await cursor.execute(operation, *args, **kwargs)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\aiomysql\cursors.py", line 239, in execute
    await self._query(query)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\aiomysql\cursors.py", line 457, in _query
    await conn.query(q)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\aiomysql\connection.py", line 428, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\aiomysql\connection.py", line 622, in _read_query_result
    await result.read()
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\aiomysql\connection.py", line 1105, in read
    first_packet = await self.connection._read_packet()
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\aiomysql\connection.py", line 593, in _read_packet
    packet.check_error()
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
peewee.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''10' OFFSET ''' at line 1")
2020-12-16 16:23:04 [fileLogger] [ERROR] : (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''10' OFFSET ''' at line 1")
2020-12-16 16:23:04 [tornado.access] [INFO] : 200 POST /yzg_openapi/user/list (192.168.1.134) 41.11ms
2020-12-16 16:23:08 [tornado.access] [INFO] : 200 POST /yzg_openapi/user/list (192.168.1.134) 9.02ms
2020-12-16 16:26:19 [tornado.access] [INFO] : 200 POST /yzg_openapi/user/list (192.168.1.134) 9.02ms
2020-12-16 16:33:45 [tornado.general] [INFO] : F:\lance\pythons\pythonspace\base_tornado\api\user\handler.py modified; restarting server
2020-12-16 16:34:05 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 16:34:05 [fileLogger] [INFO] : server system:Windows
2020-12-16 16:39:30 [tornado.general] [INFO] : F:/lance/pythons/pythonspace/base_tornado/server.py modified; restarting server
2020-12-16 17:20:22 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 17:20:22 [fileLogger] [INFO] : server system:Windows
2020-12-16 17:21:31 [fileLogger] [INFO]  info : server start: http://0.0.0.0:8010
2020-12-16 17:21:31 [fileLogger] [INFO]  info : server system:Windows
2020-12-16 17:25:03 logger.py [line:96] INFO server start: http://0.0.0.0:8010
2020-12-16 17:25:03 logger.py [line:96] INFO server system:Windows
[INFO][2020-12-16 17:27:34][MainThread:11780][task_id:fileLogger]
[INFO][2020-12-16 17:27:34][MainThread:11780][task_id:fileLogger]
2020-12-16 17:28:37[line:96] INFO server start: http://0.0.0.0:8010
2020-12-16 17:28:37[line:96] INFO server system:Windows
2020-12-16 17:29:04 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 17:29:04 [fileLogger] [INFO] : server system:Windows
2020-12-16 17:29:44 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 17:29:44 [fileLogger] [INFO] : server system:Windows
[INFO] 2020-12-16 17:30:24 [fileLogger] : server start: http://0.0.0.0:8010
[INFO] 2020-12-16 17:30:24 [fileLogger] : server system:Windows
2020-12-16 17:31:06 [fileLogger] [INFO] : server start: http://0.0.0.0:8010
2020-12-16 17:31:06 [fileLogger] [INFO] : server system:Windows
2020-12-17 09:20:51 [fileLogger] [INFO] 96  : server start: http://0.0.0.0:8010
2020-12-17 09:20:51 [fileLogger] [INFO] 96  : server system:Windows
2020-12-17 09:23:05 [fileLogger] [INFO]  : server start: http://0.0.0.0:8010
2020-12-17 09:23:06 [fileLogger] [INFO]  : server system:Windows
2020-12-17 09:23:38:2020-12-17 [fileLogger] [INFO]  : server start: http://0.0.0.0:8010
2020-12-17 09:23:38:2020-12-17 [fileLogger] [INFO]  : server system:Windows
2020-12-17 09:24:41 [fileLogger] [INFO] [info]  : server start: http://0.0.0.0:8010
2020-12-17 09:24:41 [fileLogger] [INFO] [info]  : server system:Windows
2020-12-17 09:25:55 [fileLogger] [INFO] [logger] [info]  : server start: http://0.0.0.0:8010
2020-12-17 09:25:55 [fileLogger] [INFO] [logger] [info]  : server system:Windows
2020-12-17 09:27:57 [fileLogger] [INFO] [server] [main]  : server start: http://0.0.0.0:8010
2020-12-17 09:27:57 [fileLogger] [INFO] [server] [main]  : server system:Windows
2020-12-17 09:31:00 [tornado.general] [INFO] [autoreload] [_check_file]  : F:\lance\pythons\pythonspace\base_tornado\utils\logger.py modified; restarting server
2020-12-17 09:31:26 [fileLogger] [INFO] server main  : server start: http://0.0.0.0:8010
2020-12-17 09:31:26 [fileLogger] [INFO] server main  : server system:Windows
2020-12-17 09:32:17 [fileLogger] [INFO] server server.py main  : server start: http://0.0.0.0:8010
2020-12-17 09:32:17 [fileLogger] [INFO] server server.py main  : server system:Windows
2020-12-17 09:33:12 [fileLogger] [INFO] F:/lance/pythons/pythonspace/base_tornado/server.py server server.py main  : server start: http://0.0.0.0:8010
2020-12-17 09:33:12 [fileLogger] [INFO] F:/lance/pythons/pythonspace/base_tornado/server.py server server.py main  : server system:Windows
2020-12-17 09:34:21 [fileLogger] [INFO] F:/lance/pythons/pythonspace/base_tornado/server.py main_46  : server start: http://0.0.0.0:8010
2020-12-17 09:34:22 [fileLogger] [INFO] F:/lance/pythons/pythonspace/base_tornado/server.py main_54  : server system:Windows
2020-12-17 09:35:00 [fileLogger] [INFO] server.py main-46  : server start: http://0.0.0.0:8010
2020-12-17 09:35:00 [fileLogger] [INFO] server.py main-54  : server system:Windows
2020-12-17 09:35:22 [fileLogger] [INFO] server.py main  46 : server start: http://0.0.0.0:8010
2020-12-17 09:35:22 [fileLogger] [INFO] server.py main  54 : server system:Windows
2020-12-17 09:36:01 [INFO] server.py main  46 : server start: http://0.0.0.0:8010
2020-12-17 09:36:01 [INFO] server.py main  54 : server system:Windows
2020-12-17 09:36:18 [fileLogger] [INFO] server.py main  46 : server start: http://0.0.0.0:8010
2020-12-17 09:36:18 [fileLogger] [INFO] server.py main  54 : server system:Windows
2020-12-31 16:23:55 [fileLogger] [INFO] server.py main  46 : server start: http://0.0.0.0:8010
2020-12-31 16:23:55 [fileLogger] [INFO] server.py main  53 : server system:Windows
2020-12-31 16:24:07 [fileLogger] [INFO] server.py main  46 : server start: http://0.0.0.0:8010
2020-12-31 16:24:07 [fileLogger] [INFO] server.py main  53 : server system:Windows
2020-12-31 16:24:14 [fileLogger] [INFO] server.py main  46 : server start: http://0.0.0.0:8010
2020-12-31 16:24:14 [fileLogger] [INFO] server.py main  53 : server system:Windows
2020-12-31 16:24:20 [fileLogger] [INFO] server.py main  46 : server start: http://0.0.0.0:8010
2020-12-31 16:24:20 [fileLogger] [INFO] server.py main  53 : server system:Windows
2020-12-31 16:24:29 [tornado.general] [INFO] autoreload.py _check_file  202 : F:/lance/pythons/pythonspace/base_tornado/server.py modified; restarting server
2021-01-05 10:16:19 [fileLogger] [INFO] server.py main  49 : server start: http://0.0.0.0:8010
2021-01-05 10:16:19 [fileLogger] [INFO] server.py main  56 : server system:Windows
2021-01-05 10:16:39 [tornado.general] [INFO] autoreload.py _check_file  202 : F:/lance/pythons/pythonspace/base_tornado/server.py modified; restarting server
2021-01-05 10:16:53 [fileLogger] [INFO] server.py main  47 : server start: http://0.0.0.0:8010
2021-01-05 10:16:53 [fileLogger] [INFO] server.py main  54 : server system:Windows
2021-01-05 10:17:30 [fileLogger] [INFO] server.py main  46 : server start: http://0.0.0.0:8010
2021-01-05 10:17:30 [fileLogger] [INFO] server.py main  53 : server system:Windows
2021-01-05 10:18:43 [fileLogger] [INFO] server.py main  46 : server start: http://0.0.0.0:8010
2021-01-05 10:18:50 [fileLogger] [INFO] server.py main  53 : server system:Windows
2021-01-05 10:18:57 [fileLogger] [INFO] server.py main  46 : server start: http://0.0.0.0:8010
2021-01-05 10:18:57 [fileLogger] [INFO] server.py main  53 : server system:Windows
2021-01-05 10:21:02 [tornado.access] [INFO] web.py log_request  2246 : 200 POST /yzg_openapi/user/list (192.168.1.134) 68.18ms
2021-01-05 10:21:37 [tornado.access] [INFO] web.py log_request  2246 : 200 POST /yzg_openapi/user/list (192.168.1.134) 13233.10ms
2021-01-05 10:21:43 [tornado.access] [INFO] web.py log_request  2246 : 200 POST /yzg_openapi/user/list (192.168.1.134) 8.02ms
2021-01-05 10:21:45 [tornado.access] [INFO] web.py log_request  2246 : 200 POST /yzg_openapi/user/list (192.168.1.134) 8.01ms
2021-01-05 10:22:17 [tornado.access] [INFO] web.py log_request  2246 : 200 POST /yzg_openapi/user/list (192.168.1.134) 29546.98ms
2021-01-05 10:24:17 [fileLogger] [INFO] server.py main  46 : server start: http://0.0.0.0:8010
2021-01-05 10:24:18 [fileLogger] [INFO] server.py main  53 : server system:Windows
2021-01-05 10:24:23 [tornado.access] [INFO] web.py log_request  2246 : 200 POST /yzg_openapi/user/list (192.168.1.134) 16.04ms
2021-01-05 10:24:26 [tornado.access] [INFO] web.py log_request  2246 : 200 POST /yzg_openapi/user/list (192.168.1.134) 7.02ms
2021-01-05 10:24:27 [tornado.access] [INFO] web.py log_request  2246 : 200 POST /yzg_openapi/user/list (192.168.1.134) 7.02ms
2021-01-05 10:28:20 [tornado.general] [INFO] autoreload.py _check_file  202 : F:\lance\pythons\pythonspace\base_tornado\databases\mysql.py modified; restarting server
2021-01-05 10:36:24 [fileLogger] [INFO] server.py main  47 : server start: http://0.0.0.0:8010
2021-01-05 10:37:14 [fileLogger] [INFO] server.py main  54 : server system:Windows
2021-01-05 10:38:31 [fileLogger] [INFO] server.py main  47 : server start: http://0.0.0.0:8010
2021-01-05 10:38:37 [fileLogger] [INFO] server.py main  54 : server system:Windows
2021-01-05 10:44:54 [tornado.access] [INFO] web.py log_request  2246 : 200 POST /yzg_openapi/user/list (192.168.1.134) 373494.07ms
2021-01-05 10:44:54 [tornado.application] [ERROR] web.py log_exception  1788 : Uncaught exception POST /yzg_openapi/user/list (192.168.1.134)
HTTPServerRequest(protocol='http', host='192.168.1.134:8010', method='POST', uri='/yzg_openapi/user/list', version='HTTP/1.1', remote_ip='192.168.1.134')
Traceback (most recent call last):
  File "F:\codes\pythonspace\project\envs\yzg_openapi\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "F:\lance\pythons\pythonspace\base_tornado\api\user\handler.py", line 79, in post
    return await self.finish()
tornado.iostream.StreamClosedError: Stream is closed
2021-01-05 10:45:00 [tornado.access] [INFO] web.py log_request  2246 : 200 POST /yzg_openapi/user/list (192.168.1.134) 2772.25ms
2021-01-05 10:45:36 [tornado.general] [INFO] autoreload.py _check_file  202 : F:/lance/pythons/pythonspace/base_tornado/server.py modified; restarting server
2021-01-05 10:51:38 [fileLogger] [INFO] server.py main  44 : server start: http://0.0.0.0:8010
2021-01-05 10:51:38 [fileLogger] [INFO] server.py main  51 : server system:Windows
2021-01-05 10:54:33 [tornado.general] [INFO] autoreload.py _check_file  202 : F:\lance\pythons\pythonspace\base_tornado\api\user\service.py modified; restarting server
2021-01-05 10:56:54 [fileLogger] [INFO] server.py main  44 : server start: http://0.0.0.0:8010
2021-01-05 10:56:54 [fileLogger] [INFO] server.py main  51 : server system:Windows
2021-01-05 10:57:02 [fileLogger] [INFO] server.py main  44 : server start: http://0.0.0.0:8010
2021-01-05 10:57:04 [fileLogger] [INFO] server.py main  51 : server system:Windows
2021-01-05 10:57:07 [tornado.access] [INFO] web.py log_request  2246 : 200 POST /yzg_openapi/user/list (192.168.1.134) 14.04ms
2021-01-05 10:57:45 [tornado.general] [INFO] autoreload.py _check_file  202 : F:\lance\pythons\pythonspace\base_tornado\api\user\service.py modified; restarting server
2021-01-05 10:58:01 [fileLogger] [INFO] server.py main  44 : server start: http://0.0.0.0:8010
2021-01-05 10:58:03 [fileLogger] [INFO] server.py main  51 : server system:Windows
2021-01-05 10:58:06 [tornado.access] [INFO] web.py log_request  2246 : 200 POST /yzg_openapi/user/list (192.168.1.134) 14.04ms
2021-01-05 10:58:18 [tornado.access] [INFO] web.py log_request  2246 : 200 POST /yzg_openapi/user/list (192.168.1.134) 5244.78ms
2021-01-05 11:00:42 [tornado.general] [INFO] autoreload.py _check_file  202 : F:\lance\pythons\pythonspace\base_tornado\api\user\service.py modified; restarting server
2021-01-06 10:46:24 [fileLogger] [INFO] server.py main  44 : server start: http://0.0.0.0:8010
2021-01-06 10:46:24 [fileLogger] [INFO] server.py main  51 : server system:Windows
2021-01-08 13:10:13 [fileLogger] [INFO] server.py main  44 : server start: http://0.0.0.0:8010
2021-01-08 13:10:13 [fileLogger] [INFO] server.py main  51 : server system:Windows
